#+TITLE: LG 27GL83A-B macOS EDID Patches

This repository contains patches for the LG 27GL83A's EDID that can be used by
macOS to configure the monitor correctly. This fixes various issues that this
monitor has with macOS when connected via HDMI that normally manifest in
off-looking colours.

The LG 27GL83A is effectively the same monitor as the LG 27GL850 (it identifies
itself as such) so these patches may work with that monitor too. You might need
to tweak the display product ID to get them working.

If you have a second, different monitor, installing these patches is relatively
safe as, if anything breaks, you can just delete them. If you don't have a
second monitor or your second monitor is another LG 27GL83A connected via the
same input, be careful. If something doesn't work you could end up without a
display and without a way to delete the patches.

* Installation
* What's Broken with the LG 27GL83A
The LG 27GL83A-B has three different EDIDs:

1. DisplayPort EDID
2. HDMI EDID with FreeSync enabled
3. HDMI EDID with FreeSync disabled

These patches only apply to the second (HDMI + FreeSync) EDID. They likely won't
work with the third EDID (FreeSync disabled) because FreeSync changes the
structure of the CEA-861 extension block.

The HDMI EDID used by the monitor contains incorrect data that causes issues
with macOS:

1. The width and height encoded in the EDID lead macOS to think that the
   monitor's size is 31".
2. The EDID says that the monitor does not use the sRGB colour space. This
   causes macOS to generate an inappropriate colour profile for the monitor that
   produces dull colours on the monitor.
3. The EDID states that the monitor supports the YCbCr 4:4:4 colour space.

The latter isn't strictly incorrect but it makes macOS prefer that colour space
over the full RGB colour space. Once the previous two issues are fixed, this
YCbCr flag results in colours that are slightly blown out. For example, the
Messages and FaceTime icons on Big Sur end up looking a lime green colour.

* What Gets Patched
The following patches are made to the HDMI (FreeSync enabled) EDID:

1. The horizontal and vertical screen sizes are corrected so that macOS reports
   the correct diagonal screen size of 27".
2. The horizontal and vertical image sizes for the three detailed timing
   descriptors are corrected so they produce a diagonal image size of 27".
3. The sRGB support flag is set in the display features bitmask so that macOS
   uses the correct colour profile.
4. The YCbCr 4:4:4 and YCbCr 4:2:2 support flags are cleared in the CEA-861
   extension block.
5. The DC_Y444 flag is cleared in the HDMI 1.4 vendor block to disable YCbCr
   4:4:4 support. This (and point 4 above) makes macOS output a full RGB 4:4:4
   signal to the monitor instead.
6. An extra display timing descriptor is inserted into the CEA-861 extension
   block that unlocks 144 Hz refresh rates over HDMI with FreeSync enabled.

* Technical Notes
** CEA-861 Extension Data Block Contents (HDMI FreeSync Enabled)
The data block section starts at byte offset 132. The contents are as follows:

| Data Block | Byte Offset | Type                     | Length / Bytes |
|------------+-------------+--------------------------+----------------|
|          1 |         132 | Audio                    |              3 |
|          2 |         136 | Video                    |             13 |
|          3 |         150 | HDMI 1.4 Vendor          |             13 |
|          4 |         164 | HDMI 2.0 Vendor          |              7 |
|          5 |         172 | YCbCr 4:2:0 Capabilities |              3 |
|          6 |         176 | AMD Vendor Data          |              8 |
|          7 |         185 | Colorimetry Data         |              3 |
|          8 |         189 | HDR Metadata             |              6 |

The data block ends at byte offset 196 where the first of 2 detailed timing
descriptors starts.

| DTD | Offset | Resolution  | Refresh Rate / Hz |
|-----+--------+-------------+-------------------|
|   1 |    196 | 2560 x 1440 |            74.971 |
|   2 |    214 | 2560 x 1440 |            59.951 |

Data block 6 is missing if FreeSync is disabled. As the patches update the two
DTDs after the data block, they won't work with FreeSync disabled because the
offsets into the DTD block will be different.

** CEA-861 Extension Data Block Contents (HDMI FreeSync Disabled)
The data block stats at byte offset 132. The contents are as follows:

| Data Block | Byte Offset | Type                     | Length / Bytes |
|------------+-------------+--------------------------+----------------|
|          1 |         132 | Audio                    |              3 |
|          2 |         136 | Video                    |             13 |
|          3 |         150 | HDMI 1.4 Vendor          |             13 |
|          4 |         164 | HDMI 2.0 Vendor          |              7 |
|          5 |         172 | YCbCr 4:2:0 Capabilities |              3 |
|          6 |         176 | Colorimetry Data         |              3 |
|          7 |         180 | HDR Metadata             |              6 |

The data block ends at offset 187 (offset 59 inside CEA block) where the first
of three detailed timing descriptors starts.

| DTD | Offset | Resolution  | Refresh Rate / Hz |
|-----+--------+-------------+-------------------|
|   1 |    187 | 2560 x 1440 |            59.951 |
|   2 |    205 | 2560 x 1440 |           119.998 |
|   3 |    223 | 2560 x 1440 |           143.999 |
